# Ref-IE、Ref-T2I、Ref-T2V、Ref-VE、VE、i2i、i2v、t2i、t2v

# t2i
python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  这是一幅引人注目的特写肖像，画面中一位女性的双手涂着铜色颜料，布满裂纹，环绕着她的脸庞。她鲜艳的蓝红色眼妆与光滑苍白的肌肤和柔和的背景形成鲜明对比，营造出一种大胆而超现实的构图。她脸上流露出一丝不确定感。"   --save_path assert/v1/text_to_imagev5.png   --max_frames  33
python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  一幅光线明亮的肖像照，照片中的中年男子戴着细框眼镜，身穿深色外套，内搭白色衬衫。他目光专注地看向一旁，温暖的光线照亮了他半张脸，而背景则隐入深邃的阴影中。他的表情沉思，略带戒备，仿佛正被突然捕捉到谈话的瞬间。在他身后，一个红黑相间的条纹靠垫增添了微妙的质感，与他额头和眼镜上明亮的高光形成对比。整幅照片的氛围沉思而富有电影感，在温暖与紧张之间取得了平衡。"   --save_path assert/v1/text_to_imagev6.png  --max_frames  33
python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  这是一幅极具戏剧性的黑白肖像，画面中一位年轻人身披兜帽，兜帽的深色褶皱勾勒出他脸庞的轮廓。他肤色的白皙和脸颊上淡淡的光泽与深邃的阴影形成鲜明的对比。他目光炯炯，直视镜头，眼神平静而坚定——既不咄咄逼人，也不卑躬屈膝，而是深邃而专注。衣料的质感清晰可见：厚实厚重，略带岁月痕迹，细微的褶皱在光线下闪烁。背景中，一片广袤无垠、略显虚化的风景暗示着开阔的空间——或许是远处的平原或水域——但细节却柔和而抽象。整幅画面的氛围静谧而有力，在脆弱与坚韧之间徘徊，每一处光影都诉说着他的故事。"   --save_path assert/v1/text_to_imagev7.png   --max_frames  33
python diffusers_Uni_Gen.py --task_type text_to_video    --prompt "text-to-video: 在一个超洁净的实验室里，超导量子比特被冷却在高大的玻璃腔室中。科学家们在曲面屏幕上实时监测量子态，他们的脸上映照出数据流微妙的蓝绿色光。"   --save_path assert/v1/text_to_video888.mp4  --save_path assert/v1/text_to_imagev7.mp4
# i2i
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/png111111.jpg --prompt "Image-editing: Rotate the camera 45° to the left to face directly in front of the room, keeping the pitch and zoom constant. During this process, do not change any objects in the scene; only adjust the viewing angle."   --save_path assert/v1/image_editv8.png
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 赛博朋克风格的肖像。这位短发女孩置身于霓虹闪烁的未来都市雨夜，脸上映照着强烈的粉色和青色霓虹光。她的皮肤上隐约可见发光的微型电路纹路，眼神锐利且带有义眼的光泽。背景是拥挤的赛博城市街道，巨大的全息投影广告和积水反射的灯光。画面色彩高饱和，充满高科技感和颓废美学，电影级质感。"      --save_path assert/v1/text_to_imagev9999.png
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 中国传统水墨画风格。这位短发女孩化身为画中人，用浓淡变化的墨色笔触勾勒身形，强调线条的苍劲与流动感。背景是晕染的云雾和极简的山水留白，不要具体的背景细节。整体画面摒弃写实光影，追求东方神韵和空灵的禅意，仿佛宣纸上的写意艺术品，只有黑、白、灰以及少许朱砂红的点缀。"     --save_path assert/v1/text_to_imagev999910.png
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 把整张图变成梵高星空风格"   --save_path assert/v1/image_edit_flux-klein2.png   --save_path assert/v1/text_to_imagev88.png
# Ref-IE
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/8899d43eac5ab65c7b77d5e099ddf55b1deeddc4e6ad5d8227ddcdaeba5beed4.png  --ref_image "assert/ecaa062fddd77f949116c37c781e218a7fc4b98f43bac9f67649a601af5d775d.png" --prompt "Image-editing: 一位优雅的女士在精品店中精心挑选一款图中精致的蓝色的包包，她在正面在介绍包包"   --save_path assert/v1/image_editv888.png
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/src2.jpg  --ref_image "assert/ref2.jpg" --prompt "Image-editing: 专业产品摄影，一位优雅的亚洲女性模特手持Lumière香水瓶，温柔地展示产品。模特拥有长卷发，精致妆容，穿着白色简约上衣，粉色背景。她微笑着将香水瓶靠近镜头，另一只手轻抚瓶身，展现产品的奢华质感。香水瓶为方形透明玻璃，金色瓶盖，粉色香水液体，标签上写着"Lumière"。柔和的影棚灯光，浅景深，高端美妆广告风格，8K超高清画质，精致细节，商业摄影质感。"   --save_path assert/v1/image_ref2edit.png
# Ref-T2I
python diffusers_Uni_Gen.py --task_type text_to_image  --max_frames 33  --ref_image "assert/ecaa062fddd77f949116c37c781e218a7fc4b98f43bac9f67649a601af5d775d.png" --prompt "text_to_image: An elegant lady is carefully selecting an exquisite blue bag from the boutique"   --save_path assert/v1/t2i_ref2edit1.png
python diffusers_Uni_Gen.py --task_type text_to_image  --max_frames 33 --ref_image "assert/ref2.jpg" --prompt "text_to_image: Asian woman in white top holding the perfume bottle from the reference image. Pink background. Commercial photography."   --save_path assert/v1/t2i_ref2edit2.png
# Ref-VE
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/output_no_audio.mp4  --ref_image assert/ref-ve.jpg  --prompt "video-editing:Reference-guided video style transfer. Transform the dancer into the exact style of the reference image: a Chinese fantasy character in a flowing light-blue and white elegant gown with golden ornaments, surrounded by glowing magical rings and floating swords. Strictly preserve the original dance movements, poses, and rhythm from the source video. Ensure temporal consistency across frames, avoid flickering, and render the background as a starry sky with clouds matching the reference."   --save_path assert/v1/video_edit_ref2.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ref-ve-src2.mp4  --ref_image assert/ref-ve.jpg  --prompt "video-editing:video-editing:ransform the video into a 3D animation style like Pixar/Disney characters. Reference the provided image for character design: convert the woman to have long wavy brown hair, wearing a black high-neck long-sleeve dress with a wide black belt.CRITICAL: Strictly preserve the original action and pose. She is sitting on a chair, holding a smartphone up to the camera to show the app interface, and talking/explaining. Do NOT change her to a standing pose or dancing. Maintain her facial expressions, lip movements, and hand gestures exactly as in the source video.Use soft 3D rendering with smooth shading, avoid flat 2D cartoon look. Ensure the phone screen remains visible in her hands. Ensure temporal consistency across frames."   --save_path assert/v1/video_edit_ref3.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ref-ve-src2.mp4  --ref_image assert/src_ref_image_1.png  --prompt "video-editing:给女孩戴上一副标志性的红色心形太阳镜。"   --save_path assert/v1/video_edit_ref4.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ref-ve-src2.mp4  --ref_image assert/src_ref_image_2.png  --prompt "video-editing:将背景替换成一幅中国水墨画，画中要描绘一座金色的大山峰耸立在翻滚的云层之上。"   --save_path assert/v1/video_edit_ref5.mp4
# t2v
python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: In the video, a woman is seen in a modern kitchen, preparing a meal. She is holding a wooden cutting board and appears to be in the process of chopping vegetables. The kitchen is well-equipped with a stainless steel sink, a countertop, and a refrigerator. On the countertop, there are various kitchen items such as a blender, a vase with flowers, and a jar of spices. The woman is dressed in a blue shirt and has a welcoming smile on her face. The overall style of the video is clean and modern, with a focus on the woman's cooking process and the kitchen's sleek design."  --save_path assert/v1/text-to-videov2.mp4
python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: The video features a woman in a white shirt, sitting in a cozy living room. She is gesturing with her hands, possibly explaining something or giving directions. The room is filled with natural light, and there are various objects scattered around, including a potted plant, a vase, and a book. The woman appears to be in a good mood, as she is smiling and seems engaged in the conversation. The overall style of the video is casual and relaxed, with a focus on the woman and her surroundings."  --save_path assert/v1/text-to-videov3.mp4
python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: The video features a man and a woman sitting side by side on a set with a cityscape in the background. The man is wearing a suit and tie, while the woman is dressed in a black dress. They are both seated on a white chair. The set has a blue and white color scheme. The cityscape in the background includes buildings and a street. The man and woman appear to be engaged in a conversation. The overall style of the video is professional and polished."  --save_path assert/v1/text-to-videov4.mp4
# i2v
python diffusers_Uni_Gen.py --task_type image_to_video   --src_image assert/i2v_src1.png --prompt "image-to-video: Cinematic beauty advertisement, an elegant Asian woman with long wavy hair holding a red perfume bottle with a golden cap. She gently rotates the bottle to showcase its transparent texture and luxurious design, smiling warmly and making eye contact with the camera. She speaks naturally with subtle lip movements. Slow smooth zoom-in camera movement. Soft studio lighting with pink background, high-end commercial aesthetic, 4k resolution, realistic skin texture, delicate hair movement."   --save_path assert/v1/image-to-video_cfg5.0.mp4
python diffusers_Uni_Gen.py --task_type image_to_video   --src_image assert/i2v-1_flux-klein.png --prompt "image-to-video: A cinematic, photorealistic video of a beautiful young woman standing on a snowy coastal beach at sunset. She is wearing a vibrant red V-neck wool sweater that gently flutters in the cold sea breeze, with soft fabric draping and subtle wrinkles forming as it moves, demonstrating physically plausible cloth dynamics. Her long hair flows freely around her shoulders. Gentle waves roll onto the shore, creating foamy edges, while light snowflakes fall slowly and gracefully through the air. The scene maintains a serene atmosphere with soft natural lighting, featuring high temporal coherence and a slow, smooth camera pan to the right to capture the peaceful motion."   --save_path assert/v1/image-to-video2_cfg1.0.mp4  --guidance_scale 1.0
# VE
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src1.mp4 --prompt "video-editing: Add a smiling woman with dark hair, wearing a dark purple V-neck shirt and a pearl necklace, sitting in a chair, looking towards the camera, positioned in the right half of the frame."   --save_path assert/v1/video_edit_v1.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src2.mp4 --prompt "video-editing: Replace the black book with jellyfish on the cover in her hands with a white gift box with a red ribbon and bow."   --save_path assert/v1/video_edit_v2.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src3.mp4 --prompt "video-editing: Convert the video into an Oil Impasto Painting style"   --save_path assert/v1/video_edit_v3.mp4
# Ref-T2V
python diffusers_Uni_Gen.py --task_type text_to_video --ref_image "assert/ref-t2v1_1.png"  --prompt "text-to-video: 一位优雅的女士在精品店中精心挑选一款图中精致的蓝色的包包，她在正面在介绍包包" --save_path assert/v1/ref-text-to-videov3.mp4
python diffusers_Uni_Gen.py --task_type text_to_video --ref_image assert/ref-t2v2.jpg  --prompt "text-to-video: A cute 3D cartoon girl with brown hair in a black dress riding a majestic white horse, holding a glowing URL link symbol in her hand. Background is a dreamy sky with soft clouds. Pixar style, magical atmosphere."  --save_path assert/v1/ref-text-to-videov4.mp4


