#text-to-video
python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: 一位紫发女性在舞台上表演，灯光闪烁，营造出迷幻的氛围。镜头以特写开场，聚焦于她的面部表情和上半身动作。她穿着白色吊带裙，佩戴钻石项链和耳环，红色长发随着舞蹈动作飘动。她对着镜头眨眼，并摆出各种姿势，嘴唇随着音乐节奏开合，像是在唱歌。镜头时而放大，时而缩小，突出了她的舞蹈动作和表情变化。整体风格充满动感和活力。超高清、HDR 视频、环境光、杜比全景声、画面稳定、流畅动作、逼真的细节、专业级构图、超现实主义、自然、生动、超细节、清晰。"  --save_path assert/v1/text-to-video.mp4 
python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: A purple-haired female performer is on stage, with flashing lights creating a psychedelic atmosphere. The shot opens with a close-up focusing on her facial expressions and upper body movements. She wears a white slip dress, diamond necklace and earrings, her red long hair flowing with her dance moves. She winks at the camera, strikes various poses, and her lips move in sync with the music as if she is singing. The camera zooms in and out, highlighting her dance movements and changing expressions. The overall style is dynamic and energetic. Ultra HD, HDR video, ambient lighting, Dolby Atmos, stable footage, smooth motion, realistic details, professional-grade composition, surrealism, natural, vivid, ultra-detailed, crisp.
"  --save_path assert/v1/text-to-video-en.mp4 
#text-to-image
python diffusers_Uni_Gen.py --task_type text_to_image  --prompt "text-to-image: 一位紫发女性在舞台上表演，灯光闪烁，营造出迷幻的氛围。镜头以特写开场，聚焦于她的面部表情和上半身动作。她穿着白色吊带裙，佩戴钻石项链和耳环，红色长发随着舞蹈动作飘动。她对着镜头眨眼，并摆出各种姿势，嘴唇随着音乐节奏开合，像是在唱歌。镜头时而放大，时而缩小，突出了她的舞蹈动作和表情变化。整体风格充满动感和活力。超高清、HDR 视频、环境光、杜比全景声、画面稳定、流畅动作、逼真的细节、专业级构图、超现实主义、自然、生动、超细节、清晰。"   --save_path assert/v1/text-to-image.png 
# image edit (source image + instruction)
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 将上衣修改为低胸V领款式"   --save_path assert/v1/image_edit_flux-klein.png 
# image edit (source image + instruction)
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/first_frame.jpg --prompt "Image-editing: Remove the monkey."   --save_path assert/v1/image_edit.png 
# image-to-video (animate a static image)
python diffusers_Uni_Gen.py --task_type image_to_video   --src_image assert/i2v-1_flux-klein.png --prompt "image-to-video: A cinematic, photorealistic video of a beautiful young woman standing on a snowy coastal beach at sunset. She is wearing a vibrant red V-neck wool sweater that gently flutters in the cold sea breeze, with soft fabric draping and subtle wrinkles forming as it moves, demonstrating physically plausible cloth dynamics. Her long hair flows freely around her shoulders. Gentle waves roll onto the shore, creating foamy edges, while light snowflakes fall slowly and gracefully through the air. The scene maintains a serene atmosphere with soft natural lighting, featuring high temporal coherence and a slow, smooth camera pan to the right to capture the peaceful motion."   --save_path assert/v1/image-to-video.mp4  --guidance_scale 1.0
# video edit  
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/0005e4ad9f49814db1d3f2296b911abf.mp4 --prompt "video-editing:Remove the monkey."   --save_path assert/v1/video_edit.mp4 

python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "Teaching slide. Display a progressive line of carbon‑fiber ocean‑blue disks, each slightly shorter than the last, on a neutral grey backdrop."   --save_path assert/v1/text_to_imagev1.png

python diffusers_Uni_Gen.py --task_type text_to_video    --prompt "In the video, a young woman is seen enjoying a drink in a modern, urban setting. She is wearing a vibrant red jacket and has blonde hair. The woman is holding a glass filled with a pink beverage, possibly a cocktail or a smoothie. The glass is clear, allowing the pink color of the drink to stand out. The setting appears to be a contemporary outdoor space, possibly a patio or a balcony, with a glass railing that offers a view of the cityscape. The woman is seated, and her posture suggests she is relaxed and enjoying her drink. The overall style of the video is casual and relaxed, capturing a moment of leisure in an urban environment."   --save_path assert/v1/text_to_imagev1.mp4
python diffusers_Uni_Gen.py --task_type text_to_video    --prompt "The video is a news segment featuring two individuals, a man and a woman, sitting at a desk with a blue background. The man is wearing a suit and tie, while the woman is dressed in a blazer. They are engaged in a conversation, with the man speaking and the woman listening attentively. On the desk, there are two glasses of water. The style of the video is professional and formal, typical of a news broadcast. The focus is on the two individuals and their interaction, with the background serving to highlight their presence. The lighting is bright and even, ensuring that both individuals are clearly visible. The overall impression is one of seriousness and professionalism."   --save_path assert/v1/text_to_imagev2.mp4

python diffusers_Uni_Gen.py --task_type text_to_video    --prompt "In the video, a stunning Chinese woman with long, flowing jet-black hair is enjoying a drink in a modern urban setting. She is wearing a sexy, form-fitting crimson red off-the-shoulder mini dress that accentuates her curves, paired with strappy high heels. The woman is holding a glass filled with a pink beverage, possibly a cocktail or a smoothie. The clear glass allows the pink color to stand out. The setting is a contemporary outdoor space, possibly a patio or a balcony, with a glass railing offering a view of the cityscape. She is seated, leaning back slightly, with a relaxed and confident posture, enjoying her drink. The overall style of the video is casual, chic, and relaxed, capturing a moment of urban leisure."   --save_path assert/v1/text_to_imagev2——2.mp4

python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "A cozy indoor setting where a woman is seated with a baby on her lap. The infant, dressed in a colorful outfit, gazes directly into the lens of the camera with a curious expression. The background is softly blurred, highlighting the interaction between the child and the camera."   --save_path assert/v1/text_to_imagev1222.png


python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#: A waitress informs a young couple that another table has secretly paid for their meal, causing the couple to look at each other in stunned, happy disbelief."   --save_path assert/v1/text_to_imagev2.png

python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#: 一张高速照片，捕捉职业短跑运动员在起跑线上的紧张状态，肌肉紧绷，目光专注地盯着前方的跑道。"   --save_path assert/v1/text_to_imagev4.png
python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  拍摄一位身穿海军蓝西装、满脸雀斑的红发小提琴手的头像，柔和的窗光，85mm f/1.8 镜头，温和的微笑却又带着一丝严肃的眼神，色调柔和。"   --save_path assert/v1/text_to_imagev3.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/  --max_frames  33
python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  画一个脸上带着微笑、表情严肃的、浑身是伤的拳击手。"   --save_path assert/v1/text_to_imagev4.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/  --max_frames  33


python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  这是一幅引人注目的特写肖像，画面中一位女性的双手涂着铜色颜料，布满裂纹，环绕着她的脸庞。她鲜艳的蓝红色眼妆与光滑苍白的肌肤和柔和的背景形成鲜明对比，营造出一种大胆而超现实的构图。她脸上流露出一丝不确定感。"   --save_path assert/v1/text_to_imagev5.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/  --max_frames  33

python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  一幅光线明亮的肖像照，照片中的中年男子戴着细框眼镜，身穿深色外套，内搭白色衬衫。他目光专注地看向一旁，温暖的光线照亮了他半张脸，而背景则隐入深邃的阴影中。他的表情沉思，略带戒备，仿佛正被突然捕捉到谈话的瞬间。在他身后，一个红黑相间的条纹靠垫增添了微妙的质感，与他额头和眼镜上明亮的高光形成对比。整幅照片的氛围沉思而富有电影感，在温暖与紧张之间取得了平衡。"   --save_path assert/v1/text_to_imagev6.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/  --max_frames  33

python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  这是一幅极具戏剧性的黑白肖像，画面中一位年轻人身披兜帽，兜帽的深色褶皱勾勒出他脸庞的轮廓。他肤色的白皙和脸颊上淡淡的光泽与深邃的阴影形成鲜明的对比。他目光炯炯，直视镜头，眼神平静而坚定——既不咄咄逼人，也不卑躬屈膝，而是深邃而专注。衣料的质感清晰可见：厚实厚重，略带岁月痕迹，细微的褶皱在光线下闪烁。背景中，一片广袤无垠、略显虚化的风景暗示着开阔的空间——或许是远处的平原或水域——但细节却柔和而抽象。整幅画面的氛围静谧而有力，在脆弱与坚韧之间徘徊，每一处光影都诉说着他的故事。"   --save_path assert/v1/text_to_imagev7.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/  --max_frames  33

python diffusers_Uni_Gen.py --task_type text_to_video    --prompt "text-to-video: 在一个超洁净的实验室里，超导量子比特被冷却在高大的玻璃腔室中。科学家们在曲面屏幕上实时监测量子态，他们的脸上映照出数据流微妙的蓝绿色光。"   --save_path assert/v1/text_to_video888.mp4  --save_path assert/v1/text_to_imagev7.mp4 --model_path ckpt/kiwi_edit_trained/checkpoint-step/



python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/png111111.jpg --prompt "Image-editing: Rotate the camera 45° to the left to face directly in front of the room, keeping the pitch and zoom constant. During this process, do not change any objects in the scene; only adjust the viewing angle."   --save_path assert/v1/image_editv8.png  --model_path ckpt/kiwi_edit_trained/checkpoint-step/
python diffusers_Uni_Gen.py --task_type text_to_image    --prompt "text-to-image#:  一位约 20 岁的中国女大学生，留着非常短的发型，散发出温柔而富有艺术气息的感觉。她的头发自然垂落，部分遮住脸颊，展现出一种帅气又迷人的气质。她拥有冷色调的白皙皮肤和精致的五官，表情略带羞涩却又隐含自信——嘴角微微歪斜，露出顽皮而青春的笑容。她穿着一件露肩上衣，露出一侧肩膀，身材比例匀称。画面为一张近距离自拍：她占据前景主体位置，背景清晰可见她的宿舍——上铺是一张整洁的床铺，铺着白色床单；书桌干净整齐，文具摆放有序；还有木制橱柜和抽屉。照片由智能手机拍摄，采用柔和均匀的环境光，色调自然、清晰度高，充满明亮活泼的青春日常氛围。"   --save_path assert/v1/text_to_imagev88.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/  --max_frames  33
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 赛博朋克风格的肖像。这位短发女孩置身于霓虹闪烁的未来都市雨夜，脸上映照着强烈的粉色和青色霓虹光。她的皮肤上隐约可见发光的微型电路纹路，眼神锐利且带有义眼的光泽。背景是拥挤的赛博城市街道，巨大的全息投影广告和积水反射的灯光。画面色彩高饱和，充满高科技感和颓废美学，电影级质感。"      --save_path assert/v1/text_to_imagev9999.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 中国传统水墨画风格。这位短发女孩化身为画中人，用浓淡变化的墨色笔触勾勒身形，强调线条的苍劲与流动感。背景是晕染的云雾和极简的山水留白，不要具体的背景细节。整体画面摒弃写实光影，追求东方神韵和空灵的禅意，仿佛宣纸上的写意艺术品，只有黑、白、灰以及少许朱砂红的点缀。"     --save_path assert/v1/text_to_imagev999910.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/

python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/i2v-1_flux-klein.png --prompt "Image-editing: 把整张图变成梵高星空风格"   --save_path assert/v1/image_edit_flux-klein2.png   --save_path assert/v1/text_to_imagev88.png --model_path ckpt/kiwi_edit_trained/checkpoint-step/

python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/8899d43eac5ab65c7b77d5e099ddf55b1deeddc4e6ad5d8227ddcdaeba5beed4.png  --ref_image "assert/ecaa062fddd77f949116c37c781e218a7fc4b98f43bac9f67649a601af5d775d.png" --prompt "Image-editing: 一位优雅的女士在精品店中精心挑选一款图中精致的蓝色的包包，她在正面在介绍包包"   --save_path assert/v1/image_editv888.png
python diffusers_Uni_Gen.py --task_type image_edit   --src_image assert/src2.jpg  --ref_image "assert/ref2.jpg" --prompt "Image-editing: 专业产品摄影，一位优雅的亚洲女性模特手持Lumière香水瓶，温柔地展示产品。模特拥有长卷发，精致妆容，穿着白色简约上衣，粉色背景。她微笑着将香水瓶靠近镜头，另一只手轻抚瓶身，展现产品的奢华质感。香水瓶为方形透明玻璃，金色瓶盖，粉色香水液体，标签上写着"Lumière"。柔和的影棚灯光，浅景深，高端美妆广告风格，8K超高清画质，精致细节，商业摄影质感。"   --save_path assert/v1/image_ref2edit.png

python diffusers_Uni_Gen.py --task_type text_to_image  --max_frames 33  --ref_image "assert/ecaa062fddd77f949116c37c781e218a7fc4b98f43bac9f67649a601af5d775d.png" --prompt "text_to_image: An elegant lady is carefully selecting an exquisite blue bag from the boutique"   --save_path assert/v1/t2i_ref2edit1.png
python diffusers_Uni_Gen.py --task_type text_to_image  --max_frames 33 --ref_image "assert/ref2.jpg" --prompt "text_to_image: Asian woman in white top holding the perfume bottle from the reference image. Pink background. Commercial photography."   --save_path assert/v1/t2i_ref2edit2.png


python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/output_no_audio.mp4  --ref_image assert/ref-ve.jpg  --prompt "video-editing:Reference-guided video style transfer. Transform the dancer into the exact style of the reference image: a Chinese fantasy character in a flowing light-blue and white elegant gown with golden ornaments, surrounded by glowing magical rings and floating swords. Strictly preserve the original dance movements, poses, and rhythm from the source video. Ensure temporal consistency across frames, avoid flickering, and render the background as a starry sky with clouds matching the reference."   --save_path assert/v1/video_edit_ref2.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ref-ve-src2.mp4  --ref_image assert/ref-ve.jpg  --prompt "video-editing:video-editing:ransform the video into a 3D animation style like Pixar/Disney characters. Reference the provided image for character design: convert the woman to have long wavy brown hair, wearing a black high-neck long-sleeve dress with a wide black belt.CRITICAL: Strictly preserve the original action and pose. She is sitting on a chair, holding a smartphone up to the camera to show the app interface, and talking/explaining. Do NOT change her to a standing pose or dancing. Maintain her facial expressions, lip movements, and hand gestures exactly as in the source video.Use soft 3D rendering with smooth shading, avoid flat 2D cartoon look. Ensure the phone screen remains visible in her hands. Ensure temporal consistency across frames."   --save_path assert/v1/video_edit_ref3.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ref-ve-src2.mp4  --ref_image assert/src_ref_image_1.png  --prompt "video-editing:给女孩戴上一副标志性的红色心形太阳镜。"   --save_path assert/v1/video_edit_ref4.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ref-ve-src2.mp4  --ref_image assert/src_ref_image_2.png  --prompt "video-editing:将背景替换成一幅中国水墨画，画中要描绘一座金色的大山峰耸立在翻滚的云层之上。"   --save_path assert/v1/video_edit_ref5.mp4





python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: In the video, a woman is seen in a modern kitchen, preparing a meal. She is holding a wooden cutting board and appears to be in the process of chopping vegetables. The kitchen is well-equipped with a stainless steel sink, a countertop, and a refrigerator. On the countertop, there are various kitchen items such as a blender, a vase with flowers, and a jar of spices. The woman is dressed in a blue shirt and has a welcoming smile on her face. The overall style of the video is clean and modern, with a focus on the woman's cooking process and the kitchen's sleek design."  --save_path assert/v1/text-to-videov2.mp4

python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: The video features a woman in a white shirt, sitting in a cozy living room. She is gesturing with her hands, possibly explaining something or giving directions. The room is filled with natural light, and there are various objects scattered around, including a potted plant, a vase, and a book. The woman appears to be in a good mood, as she is smiling and seems engaged in the conversation. The overall style of the video is casual and relaxed, with a focus on the woman and her surroundings."  --save_path assert/v1/text-to-videov3.mp4
python diffusers_Uni_Gen.py --task_type text_to_video  --prompt "text-to-video: The video features a man and a woman sitting side by side on a set with a cityscape in the background. The man is wearing a suit and tie, while the woman is dressed in a black dress. They are both seated on a white chair. The set has a blue and white color scheme. The cityscape in the background includes buildings and a street. The man and woman appear to be engaged in a conversation. The overall style of the video is professional and polished."  --save_path assert/v1/text-to-videov4.mp4



python diffusers_Uni_Gen.py --task_type image_to_video   --src_image assert/i2v_src1.png --prompt "image-to-video: Cinematic beauty advertisement, an elegant Asian woman with long wavy hair holding a red perfume bottle with a golden cap. She gently rotates the bottle to showcase its transparent texture and luxurious design, smiling warmly and making eye contact with the camera. She speaks naturally with subtle lip movements. Slow smooth zoom-in camera movement. Soft studio lighting with pink background, high-end commercial aesthetic, 4k resolution, realistic skin texture, delicate hair movement."   --save_path assert/v1/image-to-video_cfg5.0.mp4
python diffusers_Uni_Gen.py --task_type image_to_video   --src_image assert/i2v-1_flux-klein.png --prompt "image-to-video: A cinematic, photorealistic video of a beautiful young woman standing on a snowy coastal beach at sunset. She is wearing a vibrant red V-neck wool sweater that gently flutters in the cold sea breeze, with soft fabric draping and subtle wrinkles forming as it moves, demonstrating physically plausible cloth dynamics. Her long hair flows freely around her shoulders. Gentle waves roll onto the shore, creating foamy edges, while light snowflakes fall slowly and gracefully through the air. The scene maintains a serene atmosphere with soft natural lighting, featuring high temporal coherence and a slow, smooth camera pan to the right to capture the peaceful motion."   --save_path assert/v1/image-to-video2_cfg1.0.mp4  --guidance_scale 1.0

#00eeaef3f5acc998db34b6e23d5b7eb4eea169905c4a6ba074587bdb062f2e3e-an_Oil_Impasto_Painting_style    Convert the video into an Oil Impasto Painting style
#00b4835a077113c040ad226bbd9c11be8dc51f61cb4de03147d8c6697b1d5264  Replace the black book with jellyfish on the cover in her hands with a white gift box with a red ribbon and bow.
#0aba435276308190356ac6d430f04a204849ee435f8cf19b44344a4e269b6e78  Add a smiling woman with dark hair, wearing a dark purple V-neck shirt and a pearl necklace, sitting in a chair, looking towards the camera, positioned in the right half of the frame.

python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src1.mp4 --prompt "video-editing: Add a smiling woman with dark hair, wearing a dark purple V-neck shirt and a pearl necklace, sitting in a chair, looking towards the camera, positioned in the right half of the frame."   --save_path assert/v1/video_edit_v1.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src2.mp4 --prompt "video-editing: Replace the black book with jellyfish on the cover in her hands with a white gift box with a red ribbon and bow."   --save_path assert/v1/video_edit_v2.mp4
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src3.mp4 --prompt "video-editing: Convert the video into an Oil Impasto Painting style"   --save_path assert/v1/video_edit_v3.mp4

python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src1.mp4 --prompt "video-editing: Add a smiling woman with dark hair, wearing a dark purple V-neck shirt and a pearl necklace, sitting in a chair, looking towards the camera, positioned in the right half of the frame."   --save_path assert/v1/video_edit_v1_cfg1.0.mp4    --guidance_scale 1.0
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src2.mp4 --prompt "video-editing: Replace the black book with jellyfish on the cover in her hands with a white gift box with a red ribbon and bow."   --save_path assert/v1/video_edit_v2_cfg1.0.mp4   --guidance_scale 1.0
python diffusers_Uni_Gen.py --task_type video_edit    --video_path assert/ve_src3.mp4 --prompt "video-editing: Convert the video into an Oil Impasto Painting style"   --save_path assert/v1/video_edit_v3_cfg1.0.mp4   --guidance_scale 1.0


python diffusers_Uni_Gen.py --task_type text_to_video --ref_image "assert/ref-t2v1_1.png"  --prompt "text-to-video: 一位优雅的女士在精品店中精心挑选一款图中精致的蓝色的包包，她在正面在介绍包包" --save_path assert/v1/ref-text-to-videov3.mp4
python diffusers_Uni_Gen.py --task_type text_to_video --ref_image assert/ref-t2v2.jpg  --prompt "text-to-video: A cute 3D cartoon girl with brown hair in a black dress riding a majestic white horse, holding a glowing URL link symbol in her hand. Background is a dreamy sky with soft clouds. Pixar style, magical atmosphere."  --save_path assert/v1/ref-text-to-videov4.mp4
